# Generated by Django 5.2.7 on 2025-10-06 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0001_initial'),
        ('root_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrequest',
            name='root_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_requests', to='root_users.rootuser'),
        ),
    ]
