# Generated by Django 5.1.6 on 2025-10-07 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0002_alter_adminrequest_root_user'),
        ('root_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootUserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('root_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='root_users.rootuser')),
            ],
            options={
                'db_table': 'root_user_tokens',
            },
        ),
    ]
