from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0003_rootusertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminrequest',
            name='root_user',
        ),
    ]
# Generated by Django 5.1.6 on 2025-10-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0003_rootusertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminrequest',
            name='root_user',
        ),
    ]
