# Generated by Django 5.2.6 on 2025-10-08 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0004_remove_adminrequest_root_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AlterModelOptions(
            name='adminuser',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rootusertoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='root_user',
            new_name='root',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminrequest',
            name='email',
            field=models.EmailField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(max_length=120, unique=True),
        ),
    ]
