# Generated by Django 5.2.6 on 2025-10-01 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='debts.debt')),
            ],
            options={
                'db_table': 'calculations',
            },
        ),
    ]
