# Generated by Django 5.2.6 on 2025-10-01 10:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('business_name', models.CharField(max_length=150)),
                ('national_id', models.CharField(max_length=32, unique=True)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_admins', to='root_users.rootuser')),
            ],
            options={
                'db_table': 'admin_info',
            },
        ),
    ]
