# Generated by Django 5.2.6 on 2025-10-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('national_id', models.CharField(max_length=32, unique=True)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'creditors',
            },
        ),
    ]
