# Generated by Django 5.2.6 on 2025-10-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='rootuser',
            table=None,
        ),
    ]
