# Generated by Django 5.2.6 on 2025-10-01 10:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_info', '0001_initial'),
        ('creditors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INCOMPLETE', 'غير مكتمل'), ('COMPLETE', 'مكتمل')], default='INCOMPLETE', max_length=20)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='admin_info.admininfo')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='creditors.creditor')),
            ],
            options={
                'db_table': 'debts',
            },
        ),
    ]
